name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Google Cloud project ID'
        required: true
      cluster_name:
        description: 'GKE Cluster name'
        required: true
      region:
        description: 'GCP region'
        required: true
      machine_type:
        description: 'Machine type for the GKE nodes'
        required: true
      node_count:
        description: 'Initial number of nodes in the GKE cluster'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.9"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: |
        terraform apply \
          -auto-approve \
          -var="project=${{ github.event.inputs.project }}" \
          -var="region=${{ github.event.inputs.region }}" \
          -var="machine_type=${{ github.event.inputs.machine_type }}" \
          -var="node_count=${{ github.event.inputs.node_count }}" \
          -var="disk_size_gb=${{ github.event.inputs.disk_size_gb }}"
