name: GKE-Cluster-Create

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Google Cloud project ID'
        required: true
      cluster_name:
        description: 'GKE Cluster name'
        required: true
      region:
        description: 'GCP region'
        required: true
      machine_type:
        description: 'Machine type for the GKE nodes'
        required: true
      node_count:
        description: 'Initial number of nodes in the GKE cluster'
        required: true

jobs:
  Create-Cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Adjust to desired version

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

